# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions
name: 'collect public packages'
description: |
  Collects every package name in a repository that is explicitly marked as
  private: false and checks if it is published
author: 'alexaegis'
# https://github.com/haya14busa/github-action-brandings
branding:
  color: 'yellow'
  icon: 'align-left'
runs:
  using: 'node20'
  main: 'public/index.js'
inputs:
  registry:
    description: |
      What npm registry to check published versions against
      (Default: undefined, it is left to npm to decide)
outputs:
  public_packages:
    description: |
      An array of objects describing every public package
      {
        package_name: string; // Example: @foo/bar
        package_version: string;
        package_name_without_org: string; // Example: bar (no leading slash)
        package_name_only_org: string; // Example: @foo (no trailing slash)
        package_path_from_root_package: string; // Example: packages/bar (no trailing slash)
        is_published: boolean;
      }
  already_published_packages:
    description: |
      A pre-filtered array of objects describing every public package that is already published
      {
        package_name: string; // Example: @foo/bar
        package_version: string;
        package_name_without_org: string; // Example: bar (no leading slash)
        package_name_only_org: string; // Example: @foo (no trailing slash)
        package_path_from_root_package: string; // Example: packages/bar (no trailing slash)
        is_published: boolean; // Always true here
      }
  non_published_packages:
    description: |
      A pre-filtered array of objects describing every public package that is not yet published
      {
        package_name: string; // Example: @foo/bar
        package_version: string;
        package_name_without_org: string; // Example: bar (no leading slash)
        package_name_only_org: string; // Example: @foo (no trailing slash)
        package_path_from_root_package: string; // Example: packages/bar (no trailing slash)
        is_published: boolean; // Always false here
      }
