# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions
name: 'collect public packages'
description:
  'Collects every package name in a repository that is explicitly marked as
  private: false'
author: 'alexaegis'
runs:
  using: 'node16'
  main: 'public/index.js'
# https://github.com/haya14busa/github-action-brandings
branding:
  color: 'yellow'
  icon: 'align-left'
