name: manual-test

on:
  workflow_dispatch:

jobs:
  test:
    name: manual-test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: collect public packages
        id: collect-packages
        uses: ./
      - name: print collected public packages
        run: |
          echo collected packages: ${{steps.collect-packages.outputs.publicPackageNames}}
