name: simple-test

on:
  workflow_dispatch:
  push:
    branches: '**'

jobs:
  collect:
    runs-on: ubuntu-latest
    outputs:
      public_packages: ${{ steps.collect_packages.outputs.public_packages }}
      already_published_packages:
        ${{ steps.collect_packages.outputs.already_published_packages }}
      non_published_packages:
        ${{ steps.collect_packages.outputs.non_published_packages }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: collect packages
        id: collect_packages
        uses: ./
  print:
    name: |
      print ${{ matrix.package.package_name }}@${{ matrix.package.package_version }}
    runs-on: ubuntu-latest
    if: needs.collect.outputs.public_packages
    strategy:
      matrix:
        package: ${{ fromJSON(needs.collect.outputs.public_packages) }}
    needs: [collect]
    steps:
      - name: print package data
        run: |
          echo package_name: ${{ matrix.package.package_name }}
          echo package_version: ${{ matrix.package.package_version }}
          echo package_name_without_org: ${{ matrix.package.package_name_without_org }}
          echo package_name_only_org: ${{ matrix.package.package_name_only_org }}
          echo package_path_from_root_package: ${{ matrix.package.package_path_from_root_package }}
          echo is_published: ${{ matrix.package.is_published }}
