name: simple-test

on:
  workflow_dispatch:
  push:
    branches: '**'

jobs:
  collect:
    runs-on: ubuntu-latest
    outputs:
      publicPackageNames:
        ${{ steps.collectPackages.outputs.publicPackageNames }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: collect public packages
        id: collectPackages
        uses: ./
  print:
    runs-on: ubuntu-latest
    if: needs.collect.outputs.publicPackageNames
    strategy:
      matrix:
        package: ${{ fromJSON(needs.collect.outputs.publicPackageNames) }}
    needs: [collect]
    steps:
      - name: print package
        run: |
          echo package: ${{ matrix.package }}
